// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using R.Systems.Template.Infrastructure.SqlServerDb;

#nullable disable

namespace R.Systems.Template.Infrastructure.SqlServerDb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("R.Systems.Template.Infrastructure.SqlServerDb.Common.Entities.CompanyEntity", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("company", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9e27c3b4-bf21-4ffe-bdbb-919a2fc9e2cc"),
                            Name = "Meta"
                        },
                        new
                        {
                            Id = new Guid("636786f1-e5aa-4a87-9c7d-e604a92f08f5"),
                            Name = "Google"
                        });
                });

            modelBuilder.Entity("R.Systems.Template.Infrastructure.SqlServerDb.Common.Entities.ElementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int?>("AdditionalValue")
                        .HasColumnType("int")
                        .HasColumnName("additional_value");

                    b.Property<long?>("BigAdditionalValue")
                        .HasColumnType("bigint")
                        .HasColumnName("big_additional_value");

                    b.Property<long>("BigValue")
                        .HasColumnType("bigint")
                        .HasColumnName("big_value");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date")
                        .HasColumnName("creation_date");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("creation_date_time");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsNew")
                        .HasColumnType("bit")
                        .HasColumnName("is_new");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<DateOnly?>("UpdateDate")
                        .HasColumnType("date")
                        .HasColumnName("update_date");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("update_date_time");

                    b.Property<int>("Value")
                        .HasColumnType("int")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("element", (string)null);
                });

            modelBuilder.Entity("R.Systems.Template.Infrastructure.SqlServerDb.Common.Entities.EmployeeEntity", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("company_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("employee", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("424c6d87-3c97-4eb9-9a3e-0abbc7547683"),
                            CompanyId = new Guid("9e27c3b4-bf21-4ffe-bdbb-919a2fc9e2cc"),
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = new Guid("878ae60f-c657-4465-8920-9d7d34f757ed"),
                            CompanyId = new Guid("636786f1-e5aa-4a87-9c7d-e604a92f08f5"),
                            FirstName = "Will",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = new Guid("194ac2c8-72e3-4c63-8302-0217b9cc86b6"),
                            CompanyId = new Guid("636786f1-e5aa-4a87-9c7d-e604a92f08f5"),
                            FirstName = "Jack",
                            LastName = "Parker"
                        });
                });

            modelBuilder.Entity("R.Systems.Template.Infrastructure.SqlServerDb.Common.Entities.EmployeeEntity", b =>
                {
                    b.HasOne("R.Systems.Template.Infrastructure.SqlServerDb.Common.Entities.CompanyEntity", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("R.Systems.Template.Infrastructure.SqlServerDb.Common.Entities.CompanyEntity", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
