CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE company (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 3),
    name character varying(200) NOT NULL,
    CONSTRAINT "PK_company" PRIMARY KEY (id)
);

CREATE TABLE employee (
    id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 4),
    first_name character varying(100) NOT NULL,
    last_name character varying(100) NOT NULL,
    company_id integer NULL,
    CONSTRAINT "PK_employee" PRIMARY KEY (id),
    CONSTRAINT "FK_employee_company_company_id" FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE
);

INSERT INTO company (id, name)
VALUES (1, 'Meta');
INSERT INTO company (id, name)
VALUES (2, 'Google');

INSERT INTO employee (id, company_id, first_name, last_name)
VALUES (1, 1, 'John', 'Doe');
INSERT INTO employee (id, company_id, first_name, last_name)
VALUES (2, 2, 'Will', 'Smith');
INSERT INTO employee (id, company_id, first_name, last_name)
VALUES (3, 2, 'Jack', 'Parker');

CREATE UNIQUE INDEX "IX_company_name" ON company (name);

CREATE INDEX "IX_employee_company_id" ON employee (company_id);

SELECT setval(
    pg_get_serial_sequence('company', 'id'),
    GREATEST(
        (SELECT MAX(id) FROM company) + 1,
        nextval(pg_get_serial_sequence('company', 'id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('employee', 'id'),
    GREATEST(
        (SELECT MAX(id) FROM employee) + 1,
        nextval(pg_get_serial_sequence('employee', 'id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230528144325_InitDb', '7.0.4');

COMMIT;

