// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using R.Systems.Template.Infrastructure.PostgreSqlDb;

#nullable disable

namespace R.Systems.Template.Infrastructure.PostgreSqlDb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("R.Systems.Template.Infrastructure.PostgreSqlDb.Common.Entities.CompanyEntity", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("company", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("31b04626-ed12-4d79-b3d6-1430a72000d5"),
                            Name = "Meta"
                        },
                        new
                        {
                            Id = new Guid("9427a96c-a0b6-461c-814c-9c3c2bb6ff80"),
                            Name = "Google"
                        });
                });

            modelBuilder.Entity("R.Systems.Template.Infrastructure.PostgreSqlDb.Common.Entities.ElementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AdditionalValue")
                        .HasColumnType("integer")
                        .HasColumnName("additional_value");

                    b.Property<long?>("BigAdditionalValue")
                        .HasColumnType("bigint")
                        .HasColumnName("big_additional_value");

                    b.Property<long>("BigValue")
                        .HasColumnType("bigint")
                        .HasColumnName("big_value");

                    b.Property<DateOnly>("CreationDate")
                        .HasColumnType("date")
                        .HasColumnName("creation_date");

                    b.Property<DateTime>("CreationDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creation_date_time");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("numeric")
                        .HasColumnName("discount");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsNew")
                        .HasColumnType("boolean")
                        .HasColumnName("is_new");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<DateOnly?>("UpdateDate")
                        .HasColumnType("date")
                        .HasColumnName("update_date");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("update_date_time");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.ToTable("element", (string)null);
                });

            modelBuilder.Entity("R.Systems.Template.Infrastructure.PostgreSqlDb.Common.Entities.EmployeeEntity", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uuid")
                        .HasColumnName("company_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("employee", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("84b096f7-68a1-47a8-9e6a-8cfd79f0f069"),
                            CompanyId = new Guid("31b04626-ed12-4d79-b3d6-1430a72000d5"),
                            FirstName = "John",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = new Guid("ab189e89-7007-43bf-85d1-b1cc3c69c503"),
                            CompanyId = new Guid("9427a96c-a0b6-461c-814c-9c3c2bb6ff80"),
                            FirstName = "Will",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = new Guid("b82f922b-784c-40e1-b03b-476a0b447dca"),
                            CompanyId = new Guid("9427a96c-a0b6-461c-814c-9c3c2bb6ff80"),
                            FirstName = "Jack",
                            LastName = "Parker"
                        });
                });

            modelBuilder.Entity("R.Systems.Template.Infrastructure.PostgreSqlDb.Common.Entities.EmployeeEntity", b =>
                {
                    b.HasOne("R.Systems.Template.Infrastructure.PostgreSqlDb.Common.Entities.CompanyEntity", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("R.Systems.Template.Infrastructure.PostgreSqlDb.Common.Entities.CompanyEntity", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
